name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Checkout github-pages
        run: |
          git fetch origin gh-pages:gh-pages
          git worktree add __site/ gh-pages
          git -C __site/ remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/klafyvel/quaranteneuftrois.git"
          git -C __site/ config user.name "${GITHUB_ACTOR}"
          git -C __site/ config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Build
        run: make build
      - name: Check if any file changed
        run: |
          echo "Changed lines:"
          echo "$( git -C __site/ diff ^HEAD -U0 -I "Dernière ré-génération:" | grep "^[-+]\s" )"
          echo "changed_files=$( git -C __site/ diff ^HEAD -U0 -I "Dernière ré-génération:" | grep "^[-+]\s" | wc -l )" >> "$GITHUB_ENV"
      - name: Files changed!
        if: github.ref == 'refs/heads/main' && env.changed_files > 0
        run: echo "${changed_files} lines changed, deploying."
      - name: Set remote for github-pages
        if: github.ref == 'refs/heads/main' && env.changed_files > 0
        run: |
          git -C __site/ add --all
          git -C __site/ commit -a -m "J'engage la responsabilité de ma CI pour déployer une nouvelle page."
          git -C __site/ push origin --force gh-pages
      - name: Spam people
        if: github.ref == 'refs/heads/main' && env.changed_files > 0
        uses: monal-im/xmpp-notifier@master
        with: # Set the secrets as inputs
          # jid expects the bot's bare jid (user@domain)
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          server_host: ${{ secrets.server_host }}
          # Intended recipient of the notification such as a room or single user. Bare JID expected.
          recipient: ${{ secrets.recipient }}
          message: "Cocorico! Un nouveau 49:3 a été ajouté au leader-board:\n\nhttps://klafyvel.github.io/quaranteneuftrois/"
          # Boolean to indicate if correspondent should be treated as a room (true) or a single user (false)
          recipient_is_room: true
